# Generated by Django 6.0.2 on 2026-03-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_skill_description_alter_skill_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
